### ISSUE TITLE
Syntax errror in main.py

### ISSUE THREAD

**Issue by RahulPatkiWork** [AliShazly/sudoku-py#1]
`File "main.py", line 436
    cv2.imwrite(f'{file_name}_solved.{file_ext}', solved)
                                               ^
SyntaxError: invalid syntax`

I tried to run the clone on Google Colab but got the above error.The syntax however seems fine!?

**Comment by AliShazly** [comment]
So sorry for the late reply!  You may be using a python version before 3.6, where f-strings were implemented.
